app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('vehicle.urls', namespace='vehicle')),
    path('auth/', include('auth_user.urls', namespace='authentication')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('pdf/', include('pdf_writer.urls', namespace='pdf')),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path
from .views import initiatePayment, makePayment, verifyPayment

app_name = 'payment'

urlpatterns = [
  path('', initiatePayment, name='home'),
  path('create', makePayment, name='make_payment'),
  path('<str:ref>/verify', verifyPayment, name='verify_payment')
  # path('payment/')
]

pdf_writer/urls.py
from django.urls import path
from .views import index, view_pdf

app_name = 'pdf_writer'


urlpatterns = [
  path('', index, name='home'),
  path('<str:token>/', view_pdf, name='preview')
]

vehicle/urls.py
from django.urls import path
from .views import home, list_all_services_rendered, vehicle_register, service, list_all_customers, render_service, search_customers, list_all_services_rendered, maintenance_schedule, render_service_after_registration, create_new_user


app_name='vehicle'

urlpatterns = [
  path('', home, name='dashboard'),
  path('vehicle/user/create', create_new_user, name='create_new_user'),
  path('vehicle/register', vehicle_register, name='vehicle_register'),
  path('vehicle/customers', list_all_customers, name='list_of_customers'),
  path('vehicle/customers/register/render/serivce', render_service_after_registration, name='register_render_service'),
  path('vehicle/customers/query', search_customers, name='search_customer'),
  path('vehicle/customers/render/service', render_service, name='render_service'),
  path('vehicle/customers/services/rendered', list_all_services_rendered, name='list_of_services_rendered'),
  path('vehicle/service', service, name='service'),
  path('vehicle/maintenance/shedule', maintenance_schedule, name='maintenance_schedule'),
]

vehicle/models.py
from django.db import models

# Create your models here.

VEHICLE_TYPES = (
  ('toyota', 'Toyota'),
  ('nissan', 'Nissan'),
  ('vibe', 'Vibe'),
  ('v8', 'V8'),
  ('mercedes-benz', 'Mercedes-benz'),
  ('rolls', 'Rolls'),
  ('rolls royce', 'Rolls Royce'),
)
class Vehicle(models.Model):
  id = models.AutoField(primary_key=True)
  vehicle_year = models.CharField(max_length=4, blank=True)
  vehicle_type = models.CharField(choices=(VEHICLE_TYPES), max_length=15)
  vehicle_make = models.CharField(max_length=100,)
  vehicle_model = models.CharField(max_length=100,)
  vehicle_number_plate = models.CharField(max_length=100, blank=True)
  
  def __str__(self):
    return '{} {} {}'.format(self.vehicle_year, self.vehicle_make, self.vehicle_number_plate)
  
  
class Customer(models.Model):
  id = models.AutoField(primary_key=True)
  fullname = models.CharField(max_length=200)
  phone = models.CharField(max_length=10)
  email = models.EmailField(max_length=100, blank=True)
  address = models.TextField(default='no address provided', blank=True)
  vehicles = models.ManyToManyField(Vehicle, related_name='vehicles' , blank=True)
  created_at = models.DateTimeField(auto_now_add=True)
  

  def __str__(self):
    return '{} - {}'.format(self.fullname, self.created_at)
  
  @property
  def get_initials(self):
    name = self.fullname
    first_name_initial = self.fullname[0].upper()
    last_name_index = [i for i in range(len(name)) if name[i] == ' '][0] + 1
    last_name_initial = name[last_name_index]
    initials = '{}{}'.format(first_name_initial, last_name_initial)
    return initials
  
  @property
  def get_vehicle(self):
    vec =  [v for v in self.vehicles.all()]
    return 'None' if vec == [] else vec[0]
  
  
class Service(models.Model):
  id = models.AutoField(primary_key=True)
  text = models.CharField(max_length=100)
  cost = models.DecimalField(max_digits=10, decimal_places=2)
  created_at = models.DateTimeField(auto_now_add=True)
  
  def __str__(self):
    return '{} - {}'.format(self.text, self.cost)
  
  
class Maintenance(models.Model):
  id = models.AutoField(primary_key=True)
  owner = models.ForeignKey(to=Customer, related_name='user', on_delete=models.CASCADE)
  service = models.ForeignKey(to=Service, on_delete=models.CASCADE, blank=True, related_name='service')
  token = models.CharField(max_length=200, blank=True)
  created_at = models.DateTimeField(auto_now_add=True)
  
  def __str__(self):
    return '{} - T:{}'.format(self.id, self.token)
  
  
  @property
  def customer(self):
    return self.owner.fullname
  
  @property
  def contact(self):
    return self.owner.phone
  
  @property
  def vehicle(self):
    return self.owner.get_vehicle
  
  @property
  def vehicle_type(self):
    return self.owner.get_vehicle.vehicle_type
  
  @property
  def service_detail(self):
    return self.service.text

  @property
  def amount(self):
    return self.service.cost
  
  
  
  
  
class ScheduleMaintenance(models.Model):
  customer = models.OneToOneField(to=Customer, on_delete=models.CASCADE, primary_key=True, unique=True)
  date = models.DateField(auto_now_add=True)
  created_at = models.DateTimeField(auto_now=True)

vehicle/forms.py
import json
from django import forms
from django.db.models import fields
from .models import Customer, Vehicle, Service

class VehicleRegistrationForm(forms.ModelForm):
  class Meta:
    model = Vehicle
    fields = '__all__'
    
class CustomRegisterationForm(forms.ModelForm):
  class Meta:
    model = Customer
    fields = '__all__'
    exclude = ['vehicles']
    
class ServiceForm(forms.ModelForm):
  class Meta:
    model = Service
    exclude = ['created_at']
    
    
  def save(self, commit=True):
    data  = super().save(commit = False)
    print('Save-Method: ', data)
    if commit:
      data.save()
     
    return data

vehicle/views.py
from auth_user.forms import UserRegistrationForms
from vehicle.decorators import get_request_vehicle
from vehicle.utils import remove_duplicates
from helpers.funcs import serviceTokenGenerator
import json
from django.http import response
from vehicle.models import Customer, Maintenance, ScheduleMaintenance, Service, Vehicle
from django.shortcuts import get_object_or_404, render, Http404, reverse
from django.http import JsonResponse
from django.http.response import HttpResponse, HttpResponseRedirect
from .forms import CustomRegisterationForm, VehicleRegistrationForm, ServiceForm
from django.contrib.auth.decorators import login_required

# Create your views here.

@login_required(login_url='auth/login')
def home(request):
  _number_of_customers = Customer.objects.all().count()
  
  _number_of_services = Service.objects.all().count()
 
  _number_of_vehicles = Vehicle.objects.all().count()
  
  _number_of_total_maintenance = Maintenance.objects.all().count()
  
  _schedule_maintenance = ScheduleMaintenance.objects.all()
  
  
  
  
  context = {
    'data': {
      'customers': _number_of_customers,
      'services': _number_of_services,
      'vehicles': _number_of_vehicles,
      'maintenance': _number_of_total_maintenance,
      'scheduled_maintenance': _schedule_maintenance
    }
  }
  
  return render(request, 'vehicle/index.html', context)



def create_new_user(request):
  context = {}
  context['form'] = UserRegistrationForms()
  
  if request.method == 'POST':
    form = UserRegistrationForms(request.POST)
    if form.is_valid():
      res = form.save()
      print(res)
      
  return render(request, 'vehicle/create_user.html', context)


@login_required(login_url='auth/login')
def vehicle_register(request):
  
  try:
    request.session['count'] = 2
    
  except:
    request.session['count']  = 1
  
  
  vehicle_form = VehicleRegistrationForm()
  customer_form = CustomRegisterationForm();
  context = {
    'vehicle_form': vehicle_form,
    'customer_form': customer_form
  }
  
  
  if request.method == 'POST' and request.is_ajax():
    response = {}
    CUSTOMER_UNIQUE_ATTR = 'fullname'
    form_type = 'customer_form' if  CUSTOMER_UNIQUE_ATTR in request.POST.keys() else 'vehicle_form'
    
    
    if form_type == 'customer_form':
      _customer = CustomRegisterationForm(request.POST)
      if _customer.is_valid():
        c = _customer.save()
        request.session['customer'] = c.id
        
        request.session['count'] = 2
        
        response = {
          'status': 'success',
          'status_code': 201,
          'data': {
          'customerVNumPlate': c.id,
          'customerName': c.fullname  
          },
          
        }
        return JsonResponse(response)
    
      else:
        print('Customer Error: ', _customer.errors.as_json)
        return JsonResponse({'data': [], 'status': 'error', 'status_code': 404})
    
    if form_type is not customer_form:
      _vehicle = VehicleRegistrationForm(request.POST)
      if _vehicle.is_valid():
        
        ## save vehicle 
        v = _vehicle.save()
        request.session['customerVNumPlate'] = v.vehicle_number_plate
        ## add to customer
        _customer = Customer.objects.get(id = request.session['customer'])
        _customer.vehicles.add(v)
        _customer.save()
        
        ## sessions
        # del request.session['customer']
        request.session['count'] = 1

        response = {
          'status': 'success',
          'status_code': 201,
          'data': v.vehicle_make
        }
        return JsonResponse(response)
        # return HttpResponseRedirect(reverse('vehicle:register_render_service'))
      # print('Vehicle Error: ', _vehicle.errors.as_json)
      return JsonResponse({'data': [], 'status': 'error', 'status_code': 404})

  
  
  return render(request, 'vehicle/register_vehicle.html', context)

@login_required(login_url='auth/login')
@get_request_vehicle
def service(request):
  context = {}
  form = ServiceForm();

  services =  Service.objects.all()
  context['services'] = services
  context['form'] = form
  
  if request.method == 'GET' and request.is_ajax():
    
    res = {"status": 'success', 'data': list(services.values())}
    return JsonResponse(res)
  
  
  if request.method == 'POST':
    form = ServiceForm(data=request.POST);
    if form.is_valid():
      form.save()
      
      
      response = {
        'status': 'success',
        'data': {
          "text": form.cleaned_data.get('text'),
          "amount": form.cleaned_data.get('cost'),
          },
      }
      return JsonResponse(response)
    else:
      return JsonResponse({'message': 'Data was not saved successfully', 'errors' : form.non_form_error})

  return render(request, 'vehicle/services.html', context)



@login_required(login_url='auth/login')
def list_all_customers(request):
  qs = Customer.objects.all()
  context = {
    'customers': qs
  }
  return render(request, 'vehicle/list_customers.html', context)

@login_required(login_url='auth/login')
def list_all_services_rendered(request):
  
  context = { }
  qs = Maintenance.objects.all()
  qs = remove_duplicates(qs)
  if request.method == 'POST':
  
    qs = Maintenance.objects.filter(token=request.POST['token'])
    qs.delete()
    qs = Maintenance.objects.all()
    qs = remove_duplicates(qs)
    
  context['services_rendered'] = qs
  
  return render(request, 'vehicle/service_rendered.html', context)

@login_required(login_url='auth/login')
def render_service(request):
  if request.method == 'GET' and request.is_ajax():
    # cust = Customer.objects.get(id =1)
    data_key = [key for key in request.GET.keys()][1]
    data = request.GET.get(data_key).split(' ')
    customer = get_object_or_404(Customer, fullname=request.session['customer'])
    _token = serviceTokenGenerator()
    for dt in data:
      _service = Service.objects.get(id = dt)
      _maintenance = Maintenance.objects.create(owner=customer,service=_service,token=_token)
      _maintenance.save()
    
    print('Its ajax request')
    
    return JsonResponse({'status': 'success', 'status_code': 201, 'data': {'token': _token}})
  return render(request, 'vehicle/maintenance.html')

@login_required(login_url='auth/login')
def search_customers(request):
  qs_services = Service.objects.all()
  queryset = []
  if request.method == 'POST' and not request.is_ajax():
    search_text = request.POST.get('search-text')
    search_type = request.POST.get('search-type')
    
    if search_type == 'name':
      try:
        queryset = Customer.objects.get(fullname = search_text)
      except:
        queryset = None
    
    if search_type == 'phone_number':
      try:

        queryset = Customer.objects.get(phone = search_text)
        
      except:
          queryset = None
    
    if search_type == 'number_plate':
      try:
        queryset = Customer.objects.get(vehicles__vehicle_number_plate = search_text)
      except:
        queryset = None
        
        
    if queryset is None:
      return render(request, 'vehicle/maintenance.html')
  
  print("QUERY: ", queryset)
  
  request.session['customer']  = queryset.fullname if hasattr(queryset, 'fullname') else ''

  context = {
    'data': {
      'customer': queryset,
      'services': qs_services,
    }
  }
  return render(request, 'vehicle/maintenance.html', context)


def render_service_after_registration(request):
  qs_services = Service.objects.all()
  queryset = []
  print('ID', request.session['customerVNumPlate'])

  if request.session['customerVNumPlate'] != '':
    try:
      queryset = Customer.objects.get(vehicles__vehicle_number_plate = request.session['customerVNumPlate'])
    except:
      queryset = None
      
      
  if queryset is None:
    return render(request, 'vehicle/maintenance.html')

  print("QUERY: ", queryset)
  
  request.session['customer']  = queryset.fullname if hasattr(queryset, 'fullname') else ''

  context = {
    'data': {
      'customer': queryset,
      'services': qs_services,
    }
  }
  print(context)
  return render(request, 'vehicle/maintenance.html', context)




#*** Schedule Custom ***#
@login_required(login_url='auth/login')
def maintenance_schedule(request):
  context = {}
  qs = None
  if request.method == 'POST':
    print(request.POST['customer'])
    try:
      customer = Customer.objects.get(id=request.POST['customer'])
      schedule = ScheduleMaintenance.objects.create(customer = customer)
      schedule.save()
    except:
      print('Customer already is in the schedule')
    
  qs = ScheduleMaintenance.objects.all()
  context['customers'] = qs 
  print(context['customers'])
    
  return render(request, 'vehicle/maintenance_schedule.html', context)

vehicle/templates/vehicle/blank.html
{% extends "admin_base.html" %}

{% block Title %}
  Register Vehicle
{% endblock Title %}

{% block Content %}
  
  <div class="container">
    <h3 class="display-3">Register Vechicle</h3>
  </div>
{% endblock Content %}

vehicle/templates/vehicle/create_user.html
{% extends "admin_base.html" %}

{% block Title %}
  Register Vehicle - User Creation
{% endblock Title %}

{% block Content %}
  
  <div class="container">
    <h3 class="display-3">Create new user</h3>
    <div class="row">
      <div class="col-md-6">
        <div class="card p-4">
          <form action="" method="post">
            {% csrf_token %}
            {{form}}
            <br>
            <button type="submit" class="btn btn-primary">Register user</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock Content %}

{% block Script %}
  <script>
    $(document).ready(function(){
      $('input').addClass('form-control')
      $('.helptext').hide()
    })
  </script>
{% endblock Script %}

vehicle/templates/vehicle/list_customers.html
{% extends "admin_base.html" %}

{% block Title %}
  Register Vehicle
{% endblock Title %}

{% block Content %}
  
  <div class="container">
    <h3 class="display-5 py-4">All Customers</h3>
    <div class="card shadow p-4">
      <table id="customer-table" class="table table-striped">
        <thead>
          <tr>
            <th>Name</th>
            <th>Phone</th>
            <th>Address</th>
            <th>Vehicle</th>
            <th>Options</th>
          </tr>
        </thead>
        
        <tbody>
          {% if customers %}
            {% for customer in customers  %}
              <tr>
                <td>{{customer.fullname}}</td>
                <td>{{customer.phone}}</td>
                <td>{{customer.address}}</td>
                <td>{{customer.get_vehicle}}</td>
                <td class='text-danger d-flex'>
                  <form action='{% url "vehicle:maintenance_schedule" %}' method="post">
                    {% csrf_token %}
                    <input type="checkbox" checked class='invisible' name="customer" value="{{customer.id}}" id="">
                    <button type="submit" class='btn btn-warning text-white delete-service'">
                      <i class='fa fa-calendar-o'></i>
                    </a>
                  </form>
                  <!-- <button class='btn btn-danger text-white delete-service'  id = "##${customer.id}">
                    <i class='fa fa-trash'></i>
                  </button>
                </td> -->
              </tr>
            {% endfor %}
          {% endif %}
        </tbody>
      </table>
      {% if customers is None %}
        <div class="text-center d-flex flex-column justify-content-center gap-3" id="no-data">
          <div class="no-data-image">
            <img class='' width='30%' src="http://127.0.0.1:8000/media/svg/no-data.svg" />
          </div>
          <small>No data</small>
        </div>
      {% endif %}
    </div>
  </div>
{% endblock Content %}

{% block Script %}
  <script>
    $('document').ready(function(){
      $('#customer-table').DataTable()
      $('.paginate_button').hide()
    })
  </script>
{% endblock Script %}

vehicle/templates/vehicle/maintenance.html
{% extends "admin_base.html" %}

{% block Title %}
  Register Vehicle
{% endblock Title %}

{% block Content %}
  
  <div class="container">
    <h3 class="display-5">Rendering Service</h3>
    {% if not data %}
    <div class="text-center d-flex flex-column justify-content-center gap-3 mt-4" id="no-data">
      <div class='m-auto' style='width: 400px;'>
        <img class='' width='40%' src="http://127.0.0.1:8000/media/svg/no-data.svg" />
      </div>
      <small>No data</small>
  </div>
    {% endif %}
    {% if data %}
    <div class="row">
      <div class="col-md-4">
      <div class='position-sticky' style="top: 90px;">
        <div class=" card my-4 shadow p-4 d-flex flex-column align-items-center gap-2 text-center customer-card" >
          <h4 class='customer-card__title'>Customer</h4>
          <div class="customer-initial">
            <p>{{data.customer.get_initials}}</p>
          </div>
          <h6><i>{{data.customer.fullname}}</i></h6>
          <p>{{data.customer.address}}</p>
          <p><b>{{data.customer.phone}}</b></p>
          <small class="text-muted">
            <blockquote>{{data.customer.get_vehicle}}</blockquote>
          </small>
        </div>
        <a target='blank' href="{% url 'pdf_writer:preview' 'token'  %}" id="print-btn" class="btn btn-outline-primary  my-2 shadow p-4 d-flex flex-column align-items-center gap-2 text-center customer-card">
    
           <label for="" class="" style="font-size: 1.5rem;">Print <i class="fa fa-print"></i> </label>

        </a>
        <a href="{% url 'payment:home'  %}" id="payment-btn" class="btn btn-outline-warning  my-2 shadow p-4 d-flex flex-column align-items-center gap-2 text-center customer-card">
    
           <label for="" class="" style="font-size: 1.5rem;">Make payment <i class="fa fa-money"></i> </label>

        </a>
      </div>
      </div>
      <!-- sdf -->
      <div class="col-md-8 mt-4">
        <div class="scroll">
          <!-- SERVICES CARD -->
          <div class="service-rendered pb-4">
            {% for service in data.services  %}
            <div id="service-{{service.id}}" class="card service-card shadow p-4">
              <div class="row">
                <div class="col-4">
                  <div class="image-container">
                    <img class=''  src="http://127.0.0.1:8000/media/svg/car.svg" />
                  </div>
                </div>
                <div class="col-8 ">
                  <h6><b>Service:</b></h6>
                  <p id="service-text" class="py-2">{{service.text}}</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <small id="service-cost">GHc<span>{{service.cost}}</span></small>
                    <button class="btn btn-default ml-auto">
                      <i class="fa fa-check"></i>
                    </button>
                  </div>
                </div>
              </div>
            </div>
            {% endfor %}
          </div>

          <!-- TABLE -->
          <div class="card">
            <div class="card-header bg-primary text-white text-center py-4">
              <p>Maintenance</p>
            </div>
            <div class="card-body">
              <table class="table table-striped table-hover" id="maintenance-table">
                <thead>
                  <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Cost</th>
                    <th scope="col">Action</th>
                  </tr>
                </thead>
                <tbody>
                  
                </tbody>
                <caption>
                  <div class="d-flex justify-content-between">
  
                    <h5>Total: </h5>
                    <p id="table-total">GHc<span>0</span></p>
                  </div>
                  {% if data.customer %}
                    <div class='py-2'>
                      <input type="checkbox" checked name="url" id="get-url" value='{% url "vehicle:render_service" %}' class="invisible">
                      <button id="service-submit" class="btn btn-outline-primary">submit</button>
                    </div>
                  {% endif %}
                </caption>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endif %}
  </div>
{% endblock Content %}

vehicle/templates/vehicle/register_vehicle.html
{% extends "admin_base.html" %}
{% load crispy_forms_tags %}
{% block Title %}
  Register Vehicle
{% endblock Title %}

{% block Content %}

<div class="container">
    <!-- MODAL DIALOG -->
    <div class="d-flex align-items-center justify-content-between">
      <h3 class="display-5 py-4">Register Vechicle</h3>
      <div>
        <a href="{% url 'vehicle:list_of_customers' %}" class="btn btn-outline-primary"><i class="fa fa-users"></i> List of Customers</a>
      </div>
    </div>
    <div class="row">
      <!-- CUSTOMER FORM -->
      <div class="col-md-6">
        <div class="card shadow py-4 px-5">
          <h3>Create a customer</h3>
          
          <form action="{% url 'vehicle:vehicle_register' %}" method="POST" class="pt-4" id='customer-form'>
            {% csrf_token %}
            {{customer_form|crispy}}
            <div class="d-flex justify-content-end">
              <button type='submit' class="btn btn-primary">continue <i class="fa fa-chevron-right"></i></button>
            </div>
          </form>
        </div>
      </div>
      <!-- VEHICLE FORM -->
      <div class="col-md-6">
        <div class="card shadow py-4 px-5" id="vehicle-form-parent">
          <h5>New Vehicle</h5>
          <form action="{% url 'vehicle:vehicle_register' %}" method="POST" class="pt-4" class="" id="vehicle-form">
            {% csrf_token %}
            {{vehicle_form|crispy}}
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">submit</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  <!-- MODAL -->
  
{% endblock Content %}

{% block Script %}
  <script>
    $('document').ready(function(){

      const init = () => {
        /** hide vehicle forms **/
        $("#vehicle-form-parent").hide()

      }
      const alertToast = (text, success = true) => {
        const classStr = success ? 'bg-success' : 'bg-danger'
        const liveToast = document.getElementById('liveToast')
        const toast = new bootstrap.Toast(liveToast)
        $('.toast > .toast-header > .title').text('Notification ')
        $('.toast').addClass(classStr)
        $('.toast>.toast-header').addClass(classStr)
        $('.toast .toast-body').text(text)
        toast.show()
      }

      /** post function **/
      const POST = (t, success) => {
        $.ajax({
          url: t.action,
          type: 'POST',
          dataType: 'json',
          data: $(t).serialize(),
          success: success,
          error: function(err){
            alertToast('Data is not saved - ' + res.data, false)
          }
        })
      }

      function customerFormHandler(e){
        e.preventDefault()

        const success = res => {
          console.log('Success response: ', res.status)
          alertToast('Customer data saved successfully - ' + res.data)
          
          /** show vehicle forms **/
          $("#vehicle-form-parent").fadeIn(1000).show()
          this.reset();
        }

        /** POST REQUEST **/
        POST(this, success)

        console.log('CUSTOMER FORM')

       
      }
      function vehicleFormHandler(e){
        e.preventDefault()

        const success = res => {
          console.log('Success response: ', res.status)
          alertToast('Vehicle data saved successfully - ' + res.data)
          this.reset();
          window.location.replace(`{% url 'vehicle:register_render_service' %}`)
          init()
        }

        /** POST REQUEST **/
        POST(this, success)

        console.log('VEHICLE FORM')

      }


      /*** START ***/
      init()

      /** CUSTOMER FORM **/

      $('#customer-form').on('submit', customerFormHandler)
      
      /** VEHICLE FORM **/
      $('#vehicle-form').on('submit', vehicleFormHandler)

    })
  </script>
{% endblock Script %}

vehicle/templates/vehicle/service_rendered.html
{% extends "admin_base.html" %}

{% block Title %}
  Register Vehicle
{% endblock Title %}

{% block Content %}
  
  <div class="container">
    <h3 class="display-5 py-4">Scheduled Customers</h3>
    <div class="card shadow p-4">
      <table id="customer-table" class="table table-striped">
        <thead>
          <tr>
            <th>#</th>
            <th>Invoices#</th>
            <th>Name</th>
            <th>Phone</th>
            <th>Vehicle</th>
            <th>Maintenance</th>
            <th>Cost</th>
            <th>Options</th>
          </tr>
        </thead>
        
        <tbody>
          {% if services_rendered %}
            {% for rendered in services_rendered  %}
              <tr>
                <td>{{rendered.id}}</td>
                <td>{{rendered.token}}</td>
                <td>{{rendered.customer}}</td>
                <td>{{rendered.contact}}</td>
                <td>{{rendered.vehicle}}</td>
                <td>{{rendered.service_detail}}</td>
                <td>{{rendered.amount}}</td>
                <td class='text-danger d-flex'>
                  <a target='blank' href='{% url "pdf_writer:preview" rendered.token %}' class='btn btn-outline-success delete-service'  id = "##${rendered.token}">
                    <i class='fa fa-eye'></i>
                  </a>
                  <form action="" method="post">
                    {% csrf_token %}
                    <input class="invisible" type="checkbox" name="token" value="{{rendered.token}}" checked id="">
                    <button class='btn btn-danger text-white delete-service'  id = "##">
                      <i class='fa fa-trash'></i>
                    </button>
                  </form>
                </td>
              </tr>
            {% endfor %}
          {% endif %}
        </tbody>
      </table>
      {% if services_rendered is None %}
        <div class="text-center d-flex flex-column justify-content-center align-items-center gap-3" id="no-data">
          <div class="no-data-image">
            <img class='w-50' width="50" src="http://127.0.0.1:8000/media/svg/no-data.svg" />
          </div>
          <small>No data</small>
        </div>
      {% endif %}
    </div>
  </div>
{% endblock Content %}

{% block Script %}
  <script>
    $('document').ready(function(){
      $('#customer-table').DataTable()
      $('.paginate_button').hide()
    })
  </script>
{% endblock Script %}