app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('vehicle.urls', namespace='vehicle')),
    path('auth/', include('auth_user.urls', namespace='authentication')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('pdf/', include('pdf_writer.urls', namespace='pdf')),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

auth_user/urls.py
from django.urls import path
from .views import signIn, signOut

app_name = 'auth_user'

urlpatterns = [
 path( 'login', signIn,  name='signIn'),
 path('logout', signOut, name='signOut')
]

vehicle/urls.py
from django.urls import path
from .views import home, list_all_services_rendered, vehicle_register, service, list_all_customers, render_service, search_customers, list_all_services_rendered, maintenance_schedule, render_service_after_registration, create_new_user


app_name='vehicle'

urlpatterns = [
  path('', home, name='dashboard'),
  path('vehicle/user/create', create_new_user, name='create_new_user'),
  path('vehicle/register', vehicle_register, name='vehicle_register'),
  path('vehicle/customers', list_all_customers, name='list_of_customers'),
  path('vehicle/customers/register/render/serivce', render_service_after_registration, name='register_render_service'),
  path('vehicle/customers/query', search_customers, name='search_customer'),
  path('vehicle/customers/render/service', render_service, name='render_service'),
  path('vehicle/customers/services/rendered', list_all_services_rendered, name='list_of_services_rendered'),
  path('vehicle/service', service, name='service'),
  path('vehicle/maintenance/shedule', maintenance_schedule, name='maintenance_schedule'),
]

templates/includes/footer.html
</body>
</html>

templates/includes/header.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- BOOTSTRAP CSS -->
    <link rel="stylesheet" href="{% static 'dist/plugins/bootstrap/css/bootstrap.css' %}">


    <!-- FONTAWESOME CSS -->
    <link rel="stylesheet" href="{% static 'dist/plugins/font-awesome/css/font-awesome.css' %}">
  
    <!-- CUSTOM CSS -->
    <link rel="stylesheet" href="{% static 'dist/custom/css/main.css' %}">

    <!-- DATA TABLES -->
    <link rel="stylesheet" href="{% static 'dist/plugins/data-tables/datatables.min.css' %}">
  
    <!-- JQUERY JS -->
    <script src="{% static 'dist/plugins/jquery/jquery.3.2.1.min.js' %}"></script>
  
    <!-- BOOTSTRAP JS -->
    <script src="{% static 'dist/plugins/bootstrap/js/bootstrap.js' %}"></script>

    <!-- DATA TABLE JS-->
    <script src="{% static 'dist/plugins/data-tables/datatables.min.js' %}"></script>
  
    <!-- CUSTOM JS -->
    <script  src="{% static 'dist/custom/js/main.js' %}"></script>

    <!-- TODO: try to fix the Title -->

templates/includes/navbar.html
<div class=" dashboard-content__header header shadow " style="z-index: 99999;">
  <div class="menu-toggler shadow">
    <i class="fa fa-chevron-left"></i>
  </div>
  <form action="{% url 'vehicle:search_customer' %}" method="POST" id="search-form">
    {% csrf_token %}
    <div class='search position-relative'>
      <span><i class="fa fa-search"></i></span>
      <input id='search-input' type="text" class="form-control" name="search-text">
      <button class="btn btn-default shadow" id='search-btn'>Search</button>
      <div id="search-controls" class="search-controls position-absolute px-4  py-2 start-0 top-50 d-none">
        <div>
          <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="search-type" id="inlineRadio1" value="name" checked>
            <label class="form-check-label" for="inlineRadio1">By name</label>
          </div>
          <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="search-type" id="inlineRadio2" value="number_plate">
            <label class="form-check-label" for="inlineRadio2">By number plate</label>
          </div>
          <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="search-type" id="inlineRadio3" value="phone_number">
            <label class="form-check-label" for="inlineRadio3">By phone number</label>
          </div>
        </div>
      </div>
    </div>
  </form>
  
</div>

templates/includes/sidebar.html
<div class="dashboard-sidebar">
  <div class="header">
    <div class="logo text-center">
      <h3 class='h3'>
       
        DANFOS
    
      </h3>
    </div>
  </div>
  <div class="menu position-relative">
    <p class="menu-title">General Menu</p>
    <ul class="menu-nav">
      <li class="menu-nav__item">
        <a href="{% url 'vehicle:dashboard' %}" class="menu-nav__link active">
          <div class="icon-box">
            <i class="fa fa-desktop"></i>
          </div>
          <span>Dashboard</span>
        </a>
      </li>
      <li class="menu-nav__item">
        <a href="{% url 'vehicle:vehicle_register' %}" class="menu-nav__link">
          <div class="icon-box">
            <i class="fa fa-car"></i>
          </div>
         <span> Register Vehicle</span>
        </a>
      </li>
      <li class="menu-nav__item">
        <a href="{% url 'vehicle:list_of_customers' %}" class="menu-nav__link">
          <div class="icon-box">
            <i class="fa fa-users"></i>
          </div>
         <span>Customers</span>
        </a>
      </li>
      <li class="menu-nav__item">
        <a href="{% url 'vehicle:service' %}" class="menu-nav__link">
          <div class="icon-box">
            <i class="fa fa-server"></i>
          </div>
          <span> Services</span>
        </a>
      </li>
      <li class="menu-nav__item">
        <a href="{% url 'vehicle:list_of_services_rendered' %}" class="menu-nav__link">
          <div class="icon-box">
            <i class="fa fa-server"></i>
          </div>
          <span> List of Services Rendered</span>
        </a>
      </li>

      <li class="menu-nav__item">
        <a href="{% url 'vehicle:maintenance_schedule' %}" class="menu-nav__link">
          <div class="icon-box">
            <i class="fa fa-calendar"></i>
          </div>
          <span>Maintenance Schedule</span>
        </a>
      </li>
      {% if request.user.is_superuser %}
      <li class="menu-nav__item">
        <a href="{% url 'vehicle:create_new_user' %}" class="menu-nav__link">
          <div class="icon-box">
            <i class="fa fa-user"></i>
          </div>
         <span> Create new user</span>
        </a>
      </li>
      {% endif %}
    </ul>
    <a href="{% url 'auth_user:signOut' %}" class="btn btn-outline-primary button-logout position-absolute top-100 left-0 w-100 mt-4">Logout <i class="fa fa-user"></i></a>
  </div>
</div>