app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('vehicle.urls', namespace='vehicle')),
    path('auth/', include('auth_user.urls', namespace='authentication')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('pdf/', include('pdf_writer.urls', namespace='pdf')),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path
from .views import initiatePayment, makePayment, verifyPayment

app_name = 'payment'

urlpatterns = [
  path('', initiatePayment, name='home'),
  path('create', makePayment, name='make_payment'),
  path('<str:ref>/verify', verifyPayment, name='verify_payment')
  # path('payment/')
]

payment/models.py
from django.db import models
import secrets
# Create your models here.

class Payment(models.Model):
  amount = models.PositiveIntegerField()
  ref = models.CharField(max_length=200)
  email = models.EmailField()
  verified = models.BooleanField(default=False) 
  created_at = models.DateTimeField(auto_now_add=True)
  
  
  class Meta:
    ordering = ('-created_at',)
    
  def __str__(self):
    return f'Payment: {self.amount}'
  
  
  def save(self, *args, **kwargs):
      while not self.ref:
        ref = secrets.token_urlsafe(50)
        validate_if_ref_exist = Payment.objects.filter(ref = ref)
        
        if not validate_if_ref_exist.exists():
          self.ref = ref
          
          
      super().save(*args, **kwargs)
      
### helper function
  @property
  def amount_value(self) -> int:
    return self.amount * 100

payment/forms.py
from django import forms
from .models import Payment

class PaymentForm(forms.ModelForm):
  
  class Meta:
    model = Payment
    fields = ('amount', 'email',)
  

payment/views.py
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, reverse

from payment.models import Payment
from .forms import PaymentForm
from django.conf import settings
# Create your views here.

def initiatePayment(request):
  form = PaymentForm()
  context = {}
  if request.method == 'POST':
    form = PaymentForm(request.POST)
    if form.is_valid():
      payment = form.save()
      context['paystack_public_key'] = settings.PAYSTACK_PUBLIC_KEY
      context['payment'] = payment
      return render(request, 'payment/make_payment.html', context)
    
  context['form'] = form
  return render(request, 'payment/index.html', context)


def makePayment(request):
  return render(request, 'payment/make_payment.html')


def verifyPayment(request, ref:str):
   payment = get_object_or_404(Payment, ref=ref)
   verified = payment.verify_payment()
   return HttpResponseRedirect(reverse())

payment/templates/payment/index.html
{% extends "admin_base.html" %}


{% block Content %}
  <div class='d-flex align-items-center justify-content-center' style='width:100%; height: 90vh;'>
    <div class="row">
      <div class="col-md-12">
        <div class="card shadow p-4">
          <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-primary mt-4">Submit</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock Content %}


{% block Script %}
  <script>
    $(document).ready(function(){
      $('input').addClass('form-control')
    })
  </script>
{% endblock Script %}

payment/templates/payment/make_payment.html
{% extends "admin_base.html" %}


{% block Content %}
  <div class='d-flex align-items-center justify-content-center' style='width:100%; height: 90vh;'>
    <div class="row">
      <div class="col-md-12">
        <div class="card shadow p-4">
          <h3 class="text-center">Make Payment for: <br> GH {{payment.amount}} </h3>
          <hr>
          <script src="https://js.paystack.co/v2/inline.js"></script>
          <button id="paystack-btn" class="btn btn-outline-primary">Send</button>
        </div>
      </div>
    </div>
  </div>
{% endblock Content %}


{% block Script %}
  <script>
      $(document).ready(function(){

        $('input').addClass('form-control') 


        function payWithPayStack(){
          const currency = 'GHS';
          var plan = "";
          const ref = "{{ payment.ref }}";
          let obj = {
            key: "{{ paystack_public_key }}",
            email: "{{ payment.email }}",
            amount: "{{ payment.amount_value }}",
            currency: currency,
            ref: ref,
            callback: function(response){
              window.location.href = "{% url 'payment:verify_payment' payment.ref %}"
            }
          }

   
          if(Boolean(plan)){
            obj.plan = plan;
          }

          const paystack = PaystackPop.setup(obj)
          paystack.openIframe()
        }

        $('#paystack-btn').on('click', function(){
          payWithPayStack()
        })
      })
  </script>
{% endblock Script %}